version: "3"
 
services:
  job-portal:
    container_name: job-portal
    image: "job-portal"
    ports:
      - "8080:8080"
    build: .
    # env_file:
    #   - .env
    #   - .auth.env
    depends_on:
      - postgres
    restart: always
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - db.env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=hrr
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    env_file:
      - 